### ISSUE TITLE
Add a setPageNumber / setScrollOffset function

### ISSUE THREAD

**Issue by badbenchy** [rumax/react-native-PDFView#113]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to set which page to scroll to on load so that persistence of where the user was before navigating away from PDFViewer can be stored, so on return the pdf can be loaded at the correct place

**Describe the solution you'd like**
A setScrollOffset( offset ) or setPage( pageNumber ) function

**Comment by rumax** [comment]
Hi @badbenchy , thank you for your comment and feature request. Indeed, it seems to be useful feature, but from the other side, what is the businesses case? Because we try to keep the PDF viewer as simple as possible, but stable at the same time.

Also to implement this feature, it is required to have `onPageChanged` and `onScrolled` fully implemented. Meantime `onPageChanged` is supported only on android and `onScrolled` gives only 0 and 1 offset values (which can be used to detect if the document was scrolled to the bottom).

Therefore as an option, would it be possible to create a Pull Request with implementation of this feature?
