### ISSUE TITLE
Just only follow the tutorial but shows empty screen.

### ISSUE THREAD

**Issue by motogod** [rumax/react-native-PDFView#114]
**Describe the bug**
init a new project and  just follow the tutorial but shows empty screen.

**To Reproduce**

1.npm install react-native-view-pdf --save
2.react-native link react-native-view-pdf
3.copy the code and react-native run-ios

App.js:

```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import PDFView from 'react-native-view-pdf/lib/index';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

const resources = {
  file: Platform.OS === 'ios' ? 'downloadedDocument.pdf' : '/sdcard/Download/downloadedDocument.pdf',
  url: 'https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf',
  base64: 'JVBERi0xLjMKJcfs...',
};

type Props = {};
export default class App extends Component<Props> {
  render() {
    const resourceType = 'url';

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <PDFView
          fadeInDuration={250.0}
          style={{ flex: 1 }}
          resource={'https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf'}
          resourceType={resourceType}
          onLoad={(event) => console.log(`PDF rendered from ${event}`)}
          onError={(error) => console.log('Cannot render PDF', error)}
        />
        <Text>Bottom text</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

**Expected behavior**
Show the PDF screen.

**Screenshots**
![螢幕快照 2019-04-22 下午2 24 14](https://user-images.githubusercontent.com/17781603/56487487-fb809900-650d-11e9-8236-de0cecfb53f2.png)

**Smartphone (please complete the following information):**
 - Device: simulator iPhone 6 、iPad Air2、device IPad、device Android tablet
 - RN version: 0.59.5

**Comment by rumax** [comment]
@motogod Thank you for using the PDF viewer and reporting the issue with clear description. I've tried your case and indeed it doesn't work as expected. But because you can apply the same styles to the `PDFView` as to simple `View` I've replaced in you code `PDFView` to `View`:

```
<View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <View
          style={{ flex: 1, backgroundColor: 'green' }}
        />
        <Text>Bottom text</Text>
      </View>
```

and provided the `backgroundColor`. The result was the same as in your screenshot. 

But if you add `width` style to this View, you'll see green view:

```
<View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <View
          style={{ flex: 1, backgroundColor: 'green', width: 200 }}
        />
        <Text>Bottom text</Text>
      </View>
```

And now if you revert the change with the View and use `PDFView` with width style, it will work:

```
<View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <PDFView
          fadeInDuration={250.0}
          style={{ flex: 1, width: 200 }}
          resource={'https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf'}
          resourceType={resourceType}
          onLoad={(event) => console.log(`PDF rendered from ${event}`)}
          onError={(error) => console.log('Cannot render PDF', error)}
        />
        <Text>Bottom text</Text>
      </View>
```

and rendered as

<img width="329" alt="Screen Shot 2019-04-22 at 21 49 11" src="https://user-images.githubusercontent.com/2707180/56518620-369bc000-6540-11e9-93a6-1ad7febaa005.png">

<hr>

Another solution would be to clean the style for `container`:

```
container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
```

<img width="327" alt="Screen Shot 2019-04-22 at 21 53 47" src="https://user-images.githubusercontent.com/2707180/56518847-cccfe600-6540-11e9-9748-0513338c23a4.png">


<hr>

So if you need to check the layout, try to use `View` element. I'm not sure why react doesn't render it with such styles.

**Comment by motogod** [comment]
@rumax  Thank you very much. It works and I know what is going on now. (I don't forget to start the project 😀)
