### ISSUE TITLE
startInLoadingState support?

### ISSUE THREAD

**Issue by mgcrea** [rumax/react-native-PDFView#120]
**Is your feature request related to a problem? Please describe.**

When using `<WebView />` on iOS, you can pass the `startInLoadingState` prop to have a spinner while the pdf is loading. It looks like having this spinner loading indicator is not possible out-of-the-box.

**Describe the solution you'd like**

Would be great to have something alike!

**Comment by rumax** [comment]
Hi @mgcrea, thank you for the suggestion. It sounds good, but I see some issue with it, and it is the reason why the loading indicator was not included to the project. So the issues are:

- The proposed solution is only for iOS, and as a result will not work on Android and will require additional implementation
- Is there a way to customize it? Because if you already have some custom loader on other screens it will lead to inconsistency in loaders. For this case in my project, I've used JS implementation for this.
- This native loading indicator does not cover a case when `base64` data is used, because in this case the loading state should also include loading of `base64` data

But assuming that it is possible to customize it and cover loading of `base64` data, will it be possible to create a PR?
