### ISSUE TITLE
iOS: Open files from Library and tmp folder

### ISSUE THREAD

**Issue by devattendant** [rumax/react-native-PDFView#139]
**Is your feature request related to a problem? Please describe.**
I want to store a PDF file in the /Library and /tmp directories on iOS. However in the plugin there is no way to pass a /Library or /tmp directory path to open a file from there. Is this by design or just missed?

**Describe the solution you'd like**
Opening a PDF file in the /Library and /tmp directories on iOS.

**Describe alternatives you've considered**
I thought about placing the file into /Documents but as long as it's in /tmp or /Library I do not want it to be exposed to the user.

**Additional context**
Nope.

**Comment by rumax** [comment]
Hi @devattendant, Thanks for using the PDF View component and reporting the issue. The main reason why it is implemented without `/tmp` is because we tried to make it simple enough to render the PDF documents and to be able to maintain it. 

Meantime you can check the implementation of the [RNPDFView.m](https://github.com/rumax/react-native-PDFView/blob/850d5ec3c315e94ddf8944d0a41dee025390bed2/ReactNativeViewPDF/RNPDFView.m#L113) file and try to modify it locally to check if it works for you. And if it works, would you be able to create a pull request with this change? This would be the best option for us and fastest for you, if you need this functionality. It doesn't seems to be a lot of work.

**Comment by devattendant** [comment]
Thanks, I will have a look at it. I am just getting into files on iOS, that's why I wasn't sure if there was a reason why it was not implemented.

**Comment by rumax** [comment]
Implemented in #140
