### ISSUE TITLE
Make the library backwards compatible with react-native-webview

### ISSUE THREAD

**Issue by artyorsh** [rumax/react-native-PDFView#189]
**Is your feature request related to a problem? Please describe.**

I believe it's a common practice to display all external links in the WebView component. However, Android platform is not able to render PDFs there so we need to use this package for this particular case. I want to propose use the same API as [react-native-webview](https://github.com/react-native-webview/react-native-webview) package to make it more developer-friendly, so that we don't need to use different props doing exact same things.

With current implementation, the basic usage of both components will look like this: 

```js
<PDFView resource='https://some-what.pdf' />
```

```js
<WebView source={{ uri: 'https://some-what.jpg' }} />
``` 

However, things might become more complex if you need to implement loading, error handlers and somewhat else.
Fortunately, both packages use WKWebView on iOS, so it seems it shouldn't be a problem to implement similar API and behavior.

**Comment by rumax** [comment]
Hi @artyorsh , thanks for the proposal, but to be honest I do not see a lot of benefits to use object instead of primitive type like string. The benefits of primitive properties are:
- easy to compare (oldResource === newResource, which doesn't work for oldSource === newSource)
- limited set of properties (In source you can dedfine anything, so type definition will be required)
- no issues with multiple definitions in source:

```
  const source = {
    uri: 'http://xxxx',
    file: 'file://xxxx',
  }
```

which resource should be rendered in the code above, file or uri? With primitive properties this case is not possible.

Moreover that will be a breaking change and requires development, while at this moment PDFView is stable.

In case you really need that implementation, I think you can try to do a wrapper in your code:

```
const PDFViewV2 = (props) => (
  let resource
  let resourceType;
  if (props.source.uri) {
    resource = props.source.uri;
    resourceType = 'uri';
  } else if (...) {
    // other types
  }
  return <PDFView resource={resource} resourceType={resourceType}/>;
);
```
