### ISSUE TITLE
There is no maintainer of this library !! reload function not working . Default example showing blank screen ... Very bad experience ever 

### ISSUE THREAD

**Issue by joy-mollick** [rumax/react-native-PDFView#253]
I am using example code , I was not able to make it work !! even reload() function makes Possible Unhandled Promise Rejection (id: 2) error  

<View style={{
            flex: 1,
            backgroundColor: '#F5FCFF',
        }}>
            <PDFView
                ref={pdfRef}
                fadeInDuration={250.0}
                style={{ flex: 1, width: 200}}
                resource={'https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf'}
                resourceType={'url'}
                onLoad={() => {}}
                onError={(error) => console.log('Cannot render PDF', error)}
            />
        </View>

**Comment by rumax** [comment]
Hi @joy-mollick,
Thank you for your warm feedback and [you are always welcome to contribute to the project](https://opensource.guide/how-to-contribute/) and improve the project.
 
And as a first step I would advice you can start using templates when you report the bugs. I'm not a not a magician to guess what your problem is.
Secondly and at first glance, I see that you do not use my demo project. I'm not aware what`https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf` is and where dod you take it but I'm pretty sure that none of the lib is capable of rendering 

```
Page Not Found
Sorry, We Failed this Test
The page you’re looking for may have been renamed, removed or it never existed.
```

I'm closing your issue due to lack of information. Feel free to reopen and provide more detail or create a PR with a possible fix.
