### ISSUE TITLE
CRNA Support?

### ISSUE THREAD

**Issue by kevinzhangftw** [rumax/react-native-PDFView#52]
I am using expo with CRNA, i am getting error invariant violation: native component does not exist. Cannot link with expo

Thanks

**Comment by rumax** [comment]
Thank you for the interest in the project. Unfortunately we do not support expo. According to [EJECTING](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md):

```
If you need to include a library which includes react-native link in its install instructions, there's a good chance you need to eject from CRNA.
```

Moreover official documentation says:

```
if you want to build and deploy your app yourself, you'll need to eject from CRNA and use Xcode and Android Studio.
...
If you have made use of Expo APIs while working on your project, then those API calls will stop working if you eject to a regular React Native project. If you want to continue using those APIs, you can eject to "React Native + ExpoKit" which will still allow you to build your own native code and continue using the Expo APIs. See the ejecting guide for more details about this option.
```


Therefore if you know how to do this with expo and CRNA, please, feel free to create a PR with the change to the project. Otherwise you can check for other solutions. For example, [PDF reader for Expo](https://github.com/xcarpentier/rn-pdf-reader-js).
