### ISSUE TITLE
Blank on ios device with blank screen

### ISSUE THREAD

**Issue by socheat1994** [rumax/react-native-PDFView#54]
iPhone work fine with url, but with base64 just display a bit ,than got blank. with this problem, android is working fine all condition. 
what do i miss some configuration ?.
```
                       <View style={styles.container}>
				<View style={styles.btnWrapper}>
					<View style={{ right: 15, top: 42 }} >
						<ButtonNative onPress={onClose || this.onClose} >
							<View style={styles.btn}>
								<IconCustom
									size={20}
									name="cross"
								/>
							</View>
						</ButtonNative>
					</View>
				</View>
				<PDFView
					style={styles.pdf}
					onError={(error) => console.log('onError', error)}
					onLoad={() => console.log('PDF rendered from file')}
					resource={source}
					resourceType={isBase64 ? 'base64' : 'url'}
				/>
```

**Comment by rumax** [comment]
Hi @socheat1994, do you mean that you have this issue with real device or simulator also?

From the code you gave I couldn't see anything wrong. if `source` is `base64` it should work. Didn't have such issues.

There are few options that you can try:

- Try to render the same base64 pdf, but in the [demo](https://github.com/rumax/react-native-PDFView/tree/master/demo) project. First check that it works by default and after that, replace the content of the PDF in the [base64.json](https://github.com/rumax/react-native-PDFView/blob/master/demo/base64.json) file. And this would be the best way if you can reproduce it with demo project, so that we can also reproduce and debug it.
- In your project, you can also try to render the base64 content from demo project
- Share the content of the document you want to render and we will try to render it in our projects and check if it works.

**Comment by socheat1994** [comment]
thank for reply @rumax;
I have followed you, and everything work fine. so I can know that it's problem with my style. I'm using zindex for set button on pdfview.

**Comment by Rafay3198** [comment]
facing same issue
