### ISSUE TITLE
Rotation when showing PDF results in a gray screen

### ISSUE THREAD

**Issue by jyurek** [rumax/react-native-PDFView#55]
I can display a PDF just fine. But when I rotate the phone, I get only a gray screen. Same thing if I rotate it back to portrait.

If I load the PDF in an initially-horizontal screen, it displays fine. Though, again, any rotation results in gray. Screenshots attached for the rotated views (but not the PDF itself as it's client data).

![simulator screen shot - iphone 5s - 2018-09-06 at 15 12 48](https://user-images.githubusercontent.com/4632/45179766-6b444c80-b1e7-11e8-8773-1c215b072960.png)
![simulator screen shot - iphone 5s - 2018-09-06 at 15 12 51](https://user-images.githubusercontent.com/4632/45179767-6b444c80-b1e7-11e8-8dc7-0a1a7b0375c0.png)

**Comment by sanderfrenken** [comment]
Hi jyurek, 

Sorry that this happened, it is actually a bug you found here.
I am updating the code right now, think I can publish a fix in an hour!

**Comment by sanderfrenken** [comment]
It should be fixed now, can you try using 0.3.3 and confirm whether it is working for you now?

**Comment by jyurek** [comment]
Hi, thanks for the prompt response. Unfortunately, it doesn't appear to have fixed anything.

**Comment by sanderfrenken** [comment]
That is strange, in our demo project it works now. What you can do:

- Check whether demo project works for you with rotation (maybe the issue is related to xcode/ simulator version)

- If demo project does work: 

- confirm that you are indeed using the 0.3.3 version and that it is properly linked, clean build folder in xcode etc. 
- check your code and compare the difference in pdf view rendering

Please let me know if you need any assistance or have an update!

**Comment by jyurek** [comment]
Hmm, I must have missed something when upgrading, because it works now. Sorry about the confusion, but thank you very much for the quick and useful help! :)
