### ISSUE TITLE
miss IOS pod support

### ISSUE THREAD

**Issue by milawoai** [rumax/react-native-PDFView#59]
This is a wonderful package but It has no podspec, IOS developer has to add it with library.
 I has add a podspec file so that user can use pod to import it. 
 May you give me authority to pull request?

**Comment by sanderfrenken** [comment]
Hi Milawoai,

Thanks for the compliment. 
Ofcourse we could add a podspec so that you can use cocoapods, are you able to create a PR?
Maybe just for my understanding, why would you prefer this over using npm and embed the library?
I am just curious, I see some other RN libraries also support Cocoapods, but I am wondering what is the reason for this.

regards

**Comment by rumax** [comment]
Also how do you manage dependencies on Android if you want to use Cocoapods?

**Comment by milawoai** [comment]
@rumax 
In Android We use link and gradle,
but In IOS, We uses both native and react native so we have to use pods.

**Comment by milawoai** [comment]
@sanderfrenken @rumax 

I add a PR to add podspec, please check it. Thanks for your works : )

https://github.com/rumax/react-native-PDFView/pull/60

**Comment by rumax** [comment]
Fixed with https://github.com/rumax/react-native-PDFView/pull/60
