### ISSUE TITLE
resource from assets and load indicator

### ISSUE THREAD

**Issue by esmelov** [rumax/react-native-PDFView#81]
How I can get file from assets on android and ios??? And also I would to add custom load indicator.

**Comment by sanderfrenken** [comment]
On iOS it first searches the bundle, and if it can not find it there it will look in the documentDirectory. So if you provide a valid path it should be able to discover the file. Custom loading can be acheived by showing your own custom loading view in RN and using the onLoad callback. Replace your custom load view with the render pdf view after onLoad has been called.

**Comment by rumax** [comment]
> How I can get file from assets on android and ios??? 

Did you try `file:///android_asset`?

> And also I would to add custom load indicator.

This is the goal of this library to make the PDF viewing implementation simple (https://www.pdftron.com/blog/mobile/how-to-build-a-pdf-viewer-react-native/). Actually you can do this is the same way as you do it in any other part of the app. This also guaranties that the loading indicator is consistent across the app. For example, simple search of NPM packages gives me https://www.npmjs.com/package/react-native-loading-spinner-overlay. And to have a loading state you do:

1) When you render the page set spinner state to true
2) When you get `onLoad` or `onError` it means that the loading is complete, set spinner state to false

There is also another reason to not include loading indicator to the PDF viewer - base64 data. Loading of this data is responsibility of the app, so the component cannot implement `load indicator`, and there is no reason to show loading indicator only for rendering the PDF, because it's fast enough.

**Comment by rumax** [comment]
@esmelov Please, check 0.5.5 which includes fix and demo project how to use.

**Comment by rumax** [comment]
@esmelov You can also check [demo project](https://github.com/rumax/react-native-PDFView/tree/master/demo), it includes loading state (loading indicator) now.

**Comment by esmelov** [comment]
Thank you!
