### ISSUE TITLE
PDFView fails to load local PDFs

### ISSUE THREAD

**Issue by maxammann** [rumax/react-native-PDFView#90]
**Describe the bug**
An exception is thrown when local pdfs get rendered.

The error geths thrown in this line: https://github.com/rumax/react-native-PDFView/blob/91471635edba98b87c7a462465c34a7f71758f4e/android/src/main/java/com/rumax/reactnative/pdfviewer/AsyncDownload.java#L55

```
11-27 13:07:47.613  4479  4520 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:353)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
11-27 13:07:47.613  4479  4520 E AndroidRuntime: Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at com.rumax.reactnative.pdfviewer.AsyncDownload.doInBackground(AsyncDownload.java:55)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at com.rumax.reactnative.pdfviewer.AsyncDownload.doInBackground(AsyncDownload.java:24)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-27 13:07:47.613  4479  4520 E AndroidRuntime:        ... 4 more

```

I see no problem with making this compatible with other url types. Maybe just handle the HTTPConnection case differently and revert the other way.

**To Reproduce**
Load a PDF from a local file url

**Expected behavior**
File should be loaded

**Smartphone:**
 - OS: Android

**Additional context**

This feature was implemented some time ago: https://github.com/rumax/react-native-PDFView/issues/42

**Comment by rumax** [comment]
Hi @maxammann, thank you for using the component and reporting the issue. From your description I've understood that you want to render ` local` pdf file, but the line and error says that you are trying to make a Http connection. This means that you are providing resourceType `file`, not `url`.

Can you, please, verify that you use `file` as a resourceType? It should be defined as:

```
file: {
    resource: Platform.OS === 'ios' ? 'test-pdf.pdf' : '/sdcard/Download/test-pdf.pdf',
    resourceType: 'file',
},
```

Or would be nice if you can reproduce the issue with [demo](https://github.com/rumax/react-native-PDFView/tree/master/demo) project, because after I change  resourceType from file to url, I get an error, but this is expected behaviour:

<img width="248" alt="screen shot 2018-11-28 at 20 53 36" src="https://user-images.githubusercontent.com/2707180/49178407-f7ca5b00-f34f-11e8-9f10-d506148ee1b0.png">

**Comment by maxammann** [comment]
I managed to get the resourceType: 'file' working on Android, but I was not able to load a file like this on iOS:
`/Users/integreat/Library/Developer/CoreSimulator/Devices/903F6C4F-E77E-422E-A4E0-C3B965B3C206/data/Containers/Data/Application/5EA3FC7F-8EF8-49FA-BB99-028CF66D8656/Documents/augsburg/8a3c5cbd25740.pdf`

Load a `file://` url worked in previous versions on android and ios.

If you try to load a url like `file://something` in the demo project the app will crash. This should definitely be handled somehow.

**Comment by maxammann** [comment]
Thanks for the error handling!

But I think I still can not load files like the one mentioned before on iOS. Can you verify this?

**Comment by maxammann** [comment]
Alright I got it working by just by using a relative path to the `Documents` directory.

I'm not sure how the lookup algorithm works on iOS: https://github.com/rumax/react-native-PDFView/blob/master/ReactNativeViewPDF/PDFView.m#L150

But would it be possible that some other app can place a file somewhere to override the usage of my PDF?

**Comment by sanderfrenken** [comment]
Hi maxammann, good to hear that it is working now. Indeed, you should specify a path relative to the documents dir. This is since on iOS, when your app is out there distributed via the AppStore, your app only has file system access to it's own sandbox container. Within this container, the bundle resides, and some extra directories are created for you to use as a developer to store files in, see also: 

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

Therefore, the current implementation of the pdfView will check for any given path (given the resourceType equals file) whether it exists in the documentsDirectory (https://github.com/rumax/react-native-PDFView/blob/master/ReactNativeViewPDF/PDFView.m#L150) or in the main bundle (https://github.com/rumax/react-native-PDFView/blob/master/ReactNativeViewPDF/PDFView.m#L141). 

Sidenote here, you cannot write into the bundle when your app is released. So the bundle is used for when you add a static file you want to show to your users, which is distributed in the app binary via the stores.

Well, long story short, when you write a file in your documentsDirectory on iOS, there is no way another app can read/ write at this location as well, unless the device is jail broken.

I hope this answers your question, please let me know if you need more information.

**Comment by maxammann** [comment]
@sanderfrenken thank you very much for your detailed answer. I'm not that familiar with iOS development yet :)


I think that is a feature request, but right now it would be not possible to load a PDF from `Library/Caches`, right? I can open a request then :)

**Comment by maxammann** [comment]
Will do, as soon as I start the task on our side :+1:
