### ISSUE TITLE
Support iOS App Group folder

### ISSUE THREAD

**Issue by frenberg** [rumax/react-native-PDFView#97]
Hey!

Thanks for a great lib!

I'm using this in a product I'm working on where a pdf is shared using react-native-share-extension and placed in a common folder op iOS using the App Groups capability. The file ends up in a folder like this: (the folder is accessed by react-native-fs's RNFS.pathForGroup('[app-group-id]')) and in my case:
`/private/var/mobile/Containers/Shared/AppGroup/DB1EA4BE-0FE7-4CD0-944F-A754AAE6E322/file.pdf`

This full path doesn't work as of now on iOS and as a work around I can move the file using react-native-fs from the shared folder to the document folder. But it would be sweet if it was possible to somehow point to the common folder right away.

**Comment by rumax** [comment]
Hi @frenberg, thank you for your comment. It doesn't seems to be a lot of work but will it be possible for you to create a MR with such proposal? Our current projects doesn't have such requirement, so I'm not sure when we will have some free time to implement it. You can also find a bit more information in this issue https://github.com/rumax/react-native-PDFView/issues/90, including some useful links.

**Comment by rumax** [comment]
Hi @frenberg, I've created initial implementation https://github.com/rumax/react-native-PDFView/pull/103, can you please check/debug it if it solves your issue. Or maybe you can update a demo project with the required change, so that I can debug it too.

To use it, checkout the branch and do `npm pack`. This will produce `react-native-view-pdf-0.6.4.tgz` which you can use. After that in you app add new property to the PDF viewer `fileFrom="appGroup:{CORRECT_GROUP}"`.

**Comment by rumax** [comment]
I'm closing the issue and PR #103. Please, feel free to reopen both issue and PR if this feature is really required. The best way to implement the feature would be to continue the PR #103 and implement it there or at least create a tests case in demo project, so that I can continue when I have free time.
